version: '3.4'

services:
  dev:
    image: node:14-alpine
    container_name: sn-api-node
    command:  sh -c "npm run migrate && npm run dev"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
    networks:
      - sn-network
    depends_on:
      - db

  # test:
  #   image: node:12-alpine
  #   container_name: sn_api_test
  #   command:  npm run test
  #   working_dir: /app
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./:/app:cached
  #   networks:
  #     - sn-network
  #   depends_on:
  #     - db

  db:
    image: postgres
    container_name: sn-api-node_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - sn-network

volumes:
  database:

networks:
  sn-network:
    driver: bridge